### ISSUE TITLE
asyncData error using now-builder 

### ISSUE THREAD

**Issue by CaliCastle** [Gomah/nuxt-shopify#189]
The error:
```
TypeError: n(...) is not a function
    at e.exports.global.fetch (server.js:2:422464)
    at e.fetcher (server.js:2:196611)
    at e.value (server.js:2:198382)
    at t.value (server.js:2:224516)
    at asyncData (df30ccfd100953e8f69a.js:1:10823)
```

my code in `pages/index.vue`:
```javascript
async asyncData({ $shopify }) {
    try {
      // find home page collection products
      const collection = await $shopify.collection.fetchByHandle('frontpage')
      return { products: collection.products }
    } catch (e) {
      console.error('Error while fetching product collections: ', e)
      return {}
    }
  },
```

**Comment by CaliCastle** [comment]
FIxed by adding `import 'cross-fetch/polyfill'` to the top of `nuxt.config.js` thanks for the awesome nuxt module!

**Comment by Gomah** [comment]
Thanks for reporting @CaliCastle, maybe it's because I switched to [isomorphic-unfetch](https://github.com/Gomah/nuxt-shopify/commit/96818a66aeec439434b7787e887054cf5a775bba) for 1.8.0?

Can you try using 1.7.1 or share a demo repo?
