### ISSUE TITLE
Nuxt 3 error

### ISSUE THREAD

**Issue by maxleistner** [Gomah/nuxt-shopify#984]
Any updates in nuxt3 support?

```
 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'options')                                                      11:21:42

  at shopifyModule (node_modules/nuxt-shopify/lib/module.js:3:33)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
  ```

**Comment by brandonratz** [comment]
@maxleistner Nuxt 3 is not yet supported https://github.com/Gomah/nuxt-shopify/issues/877
